{
 "title": "JMeter (for demo notes app)",
 "description": "A grafana dashboard to inspect jmeter metrics via prometheus exporter",
 "tags": [ "jmeter" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "Active Threads",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jmeter_threads{state=\"active\"}"
    }
   ]
  },
  {
   "title": "Success Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(jmeter_ratio_success[$interval]))"
    }
   ]
  },
  {
   "title": "Average Success Response Time ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((rate(jmeter_response_time_summary_sum {code=\"200\"}[$interval])/(rate(jmeter_response_time_summary_count{code=\"200\"}[$interval])>0)))",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Error (failure) rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(rate(jmeter_ratio_failure[$interval]))/avg(rate(jmeter_ratio_total[$interval])))"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Virtual Users vs OK/KO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "Virtual Users"
    },
    {
     "expr": "sum(rate(jmeter_ratio_success[$interval]))",
     "legendFormat": "Request OK per second"
    },
    {
     "expr": "sum(rate(jmeter_ratio_failure[$interval]))   ",
     "legendFormat": "Request KO per second"
    }
   ]
  },
  {
   "title": "Total Requests vs OK/KO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(jmeter_ratio_success[$interval]))/sum(rate(jmeter_ratio_total[$interval])))",
     "legendFormat": "OK"
    },
    {
     "expr": "(sum(rate(jmeter_ratio_failure[$interval]))/sum(rate(jmeter_ratio_total[$interval])))",
     "legendFormat": "KO"
    },
    {
     "expr": "sum(rate(jmeter_ratio_total[$interval]))",
     "legendFormat": "Total Requests per second"
    }
   ]
  },
  {
   "title": "Avg. Response Time vs Virtual Users",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg((rate(jmeter_response_time_summary_sum{code=\"200\"}[$interval])/(rate(jmeter_response_time_summary_count{code=\"200\"}[$interval])>0)))",
     "legendFormat": "Avg Response Time"
    },
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "Virtual Users"
    }
   ]
  },
  {
   "title": "Avg. Response Time vs OK/KO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg((rate(jmeter_response_time_summary_sum{code=\"200\"}[$interval])/(rate(jmeter_response_time_summary_count{code=\"200\"}[$interval])>0)))",
     "legendFormat": "Avg Response Time"
    },
    {
     "expr": "sum(rate(jmeter_ratio_success[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(jmeter_ratio_failure[$interval]))   ",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "OK",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(jmeter_ratio_success) by (label) "
    }
   ]
  },
  {
   "title": "KO",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(jmeter_ratio_failure) by (label) "
    }
   ]
  },
  { "title": "Response times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Avg. response time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": " avg (rate(jmeter_response_time_summary_sum{code=~\"1.*|2.*|3.*|4.*|5.*\"}[$interval]) / (rate(jmeter_response_time_summary_count{code=~\"1.*|2.*|3.*|4.*|5.*\"}[$interval])>0)) by (label)",
     "legendFormat": "{{label}} "
    }
   ]
  },
  {
   "title": "Response time (Percentile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(jmeter_response_time_summary{code=\"200\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Requests per second", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_ratio_success[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(jmeter_ratio_failure[$interval]))",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "by label",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_ratio_total[$interval])) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "by HTTP code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(jmeter_ratio_total[$interval]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "by HTTP code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (rate(Ratio_failure[$interval]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "by label",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (label) (rate(Ratio_failure[$interval]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Test farm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC % time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"jmeter\"}[1m])",
       "legendFormat": "{{instance}} - {{gc}} "
      }
     ]
    },
    {
     "title": "JVM heap  - free memory by pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(jvm_memory_pool_bytes_committed {job=~\"jmeter\"}) - (jvm_memory_pool_bytes_used{job=~\"jmeter\"}) ",
       "legendFormat": "{{instance}} - {{pool}}"
      }
     ]
    },
    {
     "title": "JVM heap -  used memory by pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(jvm_memory_pool_bytes_used{job=\"jmeter\"}) ",
       "legendFormat": "{{instance}} - {{pool}}"
      }
     ]
    },
    {
     "title": "JVM free memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(jvm_memory_bytes_max {job=\"jmeter\"}) - (jvm_memory_bytes_used{job=\"jmeter\"})",
       "legendFormat": "{{instance}} - {{area}}"
      }
     ]
    }
   ]
  }
 ]
}